import type { Metadata } from "next"
import { Merriweather } from "next/font/google"
import "./globals.css"

// Providers
import Providers from "@/lib/provider"

const merriweather = Merriweather({
    subsets: ["latin"],
    weight: ["300", "400", "400", "900"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="pt-br" suppressHydrationWarning>
            <body className={`${merriweather.className} bg-background`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
